sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

branches:
  except:
    - /^[0-9]/

after_success:
  - mvn jacoco:report coveralls:report

env:
  global:
  # Ex. travis encrypt BINTRAY_USER=your_github_account
  - secure: "HauoUZ79Jqp7BC6Irv1vEGCkzrI5+8zl8TG+i7FwlWAQG1es3YhXKSUeeWC8CkPWUZ5Yo1vqHULE+yUvYFGuVMBwPTkngbcb7Aq3mlM/Eutv1ziBH00arcKmcyc9Lm7TIaFbuCHT3JsugS9XlcO7C9olqGLOLwgmRo92H3kwRJLSdBK5xEUU0RtM26qT/FwRGMmz2reEX/uXRAMHbtBjVXoG3aNgSv60WbC2gnocrurWAAvWES2UVmFlrquF0+nI1hExIfeLjH8VtfV/6HLs7L2oXJmdHQpTJKeGlcg56u6zyRFu389ZkA/h6o7E5oNLkynRd/E+XacW1DoIUq2l5gTwWsdFsrhgOq2frpo1RbmvrBdlLsWCcFhv8F18aPlxpJNyt/pyflsCGVgQKKd9IsBVjQ4LkcgH5ZT21DNP8LFBac0zsuCD/rEBs0BStOhEGmUrLNCz+asJGRSBo6lfurVP9mx9Xkgx0HpTOba+94/H0wBpcaP0P9pS7h5Uwpv8tvrDiyud1MRP8/mwkBHzBPTUuAaYziz1AnNPT2t1+wAhgTkOgqIES8Kgf7I8Slg2A+7ZE2bAh4wvrCuh+yYaAtkulgGRmNUi1EkmzVw/GvXHVQHxhAThiN3L58OUr9IOeC//1XQsViPkUOiE2YFFwUXjPugJJnPwm8oZ1aKG62c="
  # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
  - secure: "MHwRodvL0NXCnROMBLcHCbw7Mk8HoXQlfEjTHubPlJu4qlGnu3k9CB25nM3mhqvuNj6ID9vetTftIeJKM6/YJIA6UDXxSEdVrnGiYCpsPXOXa5fyg87QsS7y45crNcKDf1G3uvUPVbckiBpQWm/mQxRtq+0PJqrBGeW87glDGehxLpydNmGRcJpI+6YVgz2IQvwZsT5GWADyu+bj3TbxLc9CzcrKev4FcZcMcbYTo1jiBth6x86SpXXIp1PnJafiNExO5V0U1E6lqihfe/uAnSqoF6swE9/yUi9KG3FTHZUfqa+O+cIJLqj2h7kSmtqmmHThrhuLS+7D5dM0CWmBkcoHb0zA0fPj0azdjbdlkOjnEiPjPT5K6cQ2DHrz0AGcdwkX90365vjRF7Rl7R/M2NzncZM/xisHVRJR71jowvc+SiQLi4b4Q+dIPrBxnUUU6BXzuKkbbTlHZJ5F0rTxlca1BymboSieuxpk88d3qqgvb772mAHv2/mXV8TOL7kX8yq+skDySQ9wwISFoK+22D5mH/32PoulwXydTLU5Zvj4xi3q+85Yl4dFHfqml+VVGXe02GaAqVHWAqmsb0q1TLu243dlrI2BzvLjCtKSjfPl3GVwXVxGV4JzpkDxA8JWGSCNbzBxd/QQjogQGuMlY3HUY9EvtAyVnpxcmxBOOAU="
  # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
  - secure: "XiCJIT+r80fnhQq5sj2oRfnqET69Bh7DirWxyn9TTrE7OxKllamg83OuVGxlwlvtx++k+MG5eBuOPjLKTz9hx01uYuBksV8+3k2s8BLSGEhnektQseUsZjnwYZY52OjTHWbojdvExRhhiiiMaMzURafCbMMmjhdssqoSxMjfelZozoz+cRFqAu2YW5kiCYc7v8NJzdMzuJrmFNtpHzPZy/0rmjvr30walpTq+laDpdsXoXiB/qJ8ZsEMqycyYRfAgEY+YdI+YNE/zgH04jGLsP5LJd8S9RP67CoxZ3iYREqwNcJr3djUv8M3zHW+3qXW9KoNM7jn4jElHk+//49zF3lBo7XTRMjBO9DDpziMs+3AE4aKnO6jjb4OgMXAK8CDilm6unwXXmBYnayMotkDSAc8tbe0xVgOLFdjFn1KaFMbMpx11cen7N4fPdbw+D1vxMQMJ++iFcb8XW8Vsi4agrfmG4SnkE5oGCTAPEQThAi3ShDgCuFu0Ro72f9mgsVpsq5thGSFkAWwYgHECRJUzXGoW3R12KCXF+1+f+cAYtTnFEPGqaX/3eYdLb08lcjitJVi9o8YQPMM9tipVxHUU20KgRtXDOTtrpA0Ye/UI2rNdjissUyD5460hcV4gZDrzaeXHwp/UIcAUGFkcg0BwgOMjqyogbJw8HKgIsdZefo="
  # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
  - secure: "r59PmY+QkDbVTSNHyZqTpCR2rqznBMzeZZYDodsLiGWdCFpR61hTUL/vFbm0jRXTXplaqDMN6OLDdm2aGlYZS1PA9ckiDtXAuocF8edi8DyTdVitDAC9XVr/dseodYnyuuf3/JVgHIX4UNe6nus2Ih4Aoppd+hg/TLoAidsFE8j7WgM5IcrYZcKAvWCsDbp81vXktlH0zeZHsqPf7j7egpY2WHFpYTz6eD8HJMv03XerMga3ReXumbRuDLXRjeSOn56DhJ1lwFzrxi5II4fbvQ8wwIsK/qls5KAJCgvQSwn9zUZE9gIxMu5ILuVq9/KU88gAxQYCa7hVcxGtkbOMYiAWXufa3IXqDfcR1hL/yZFsqbYzugkh79TfK6Z+y+5Itt387foxGFGe9JV06OQN4EwnXdQljNsf9Fehr61SIzCyPqtXQqM99CbRIkJjsxZavUIDC8emJjfxYIQ5y8XNmMeYc1R5jGkXE+RZGdEfhYCLYXPZWgJp/Q+qSisc/xWLuwbyMyTj6vD/k+gpil7ml/Ez0O8yEJJpMS3JuVl4KdYtdDq2Uz8Jl2rOBbnZm8v8KJ2roHKR0d0jSyOFzVJh+GiJ62/nmGud8hde4WpoNwYryG0oFWYucNVz3u9mGCffz31FIcRKxZrXdN7mdeuKKyZIzkUrVGr033l5S9oj0yI="
  # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
  - secure: "doj9hlexXVm64UYu+Y2/la2bxBq81qXy22CK74kV/wtlageSfsADZpE4E0WY1AO0wQYH4UCgL8LHts6lx0F2YHugnBfXBDzQNZt3aoBkCf4YTaviYyrmoOgVJRFMMv4aTiyrrhlR1EpntR0MHNh/GkLv830P+2wRglEJR8ElnOwWU8OcvAXjjW3habpwalJyv8uNKtJ9JDi8wpXJYKyRH/dU3q//2zDOyEO2dGq1CRfOHTiWj+R6qt3ym95XxHK2ZGTrziTl86qG6zYGWftvjTF2Yhu4GhsiJ9rjaGoerXgcY/WGZAOeAUgjbNNGo8sRBMqCk0k9+miI8LReFJYC4Rdmx3kVF6hQccUwkkMYAKBqP53U6JGX0VUVc82QDPwFLfFUnvCzy9jKYx4DEdQiZsQvN4l6FKuFn7Psu9g/tcijWuIGQ4NBAThlvM5YTNapGuYIx9Nw28e9oKegVtwZCWCE8w6hKiFM8alePKySvuFuFVHXuvqPGzzJf84jEFbU1DRh1rN277imshPOYa8xiC7Am6Uq5h2k+Yep8p0sNwAMp4hwZsLteEvGS5h4TCOdOSz1yAdH4G0U4OrbNv2OaTYbz4xzm81HIhxzNMNQCm4qOeGbPseywOBRwYWWj9P/ePp6T8g1DJia8B31Y8ABvJlio/b0erQ8VR8DWOvAunY="
